
import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: false,
  saveInGroup: false,
  useOCR: false,
  compressPdf: true,
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar Original",
    restore: "Restaurar Lote",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    autoCropBatch: "Recorte Automático (Sel.)",
    applyCrop: "Recortar Imagem",
    manualCrop: "Recorte Manual",
    cropInstructions: "Desenhe uma área para recortar. Arraste as bordas para ajustar.",
    processing: "Processando...",
    imageTools: "Ajustes de Imagem",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas",
    zoomIn: "Aumentar Zoom",
    zoomOut: "Diminuir Zoom",
    zoomReset: "Restaurar Zoom",
    eUndo: "Desfazer",
    eRedo: "Refazer",
    eReset: "Reset",
    backToGrid: "Voltar para Grade",
    viewPage: "Visualizar Página",
    nextPage: "Próxima",
    prevPage: "Anterior",
    batchProcessError: "Erro ao processar algumas imagens.",
    rightsReserved: "Todos os direitos reservados",
    supportLink: "Clique Aqui para obter suporte",
    footerQuote: '"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos" — Gálatas 6:9',
    brightness: "Brilho",
    contrast: "Contraste",
    adjustHelp: "Ajuste o contraste para facilitar a remoção do fundo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nova versão disponível",
    updateNow: "Atualizar",
    addPages: "Adicionar Páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Dividir e Baixar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 ou 5.",
    comingSoon: "Em breve: Digitalização (Scanner) e rotação de arquivos PDF.",
    useOCR: "OCR (Texto Pesquisável)",
    ocrWarning: "O OCR torna o processo muito mais lento",
    ocrProcessing: "Reconhecendo texto (OCR)...",
    compressPdf: "Compressão de PDF",
    about: "Sobre",
    aboutTitle: "Sobre Αρχή PDF",
    developedBy: "Criado e desenvolvido por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versão",
    manualTitle: "Manual do Usuário",
    manualIntro: "Bem-vindo ao Αρχή PDF. Aqui estão as principais funcionalidades:",
    manualOrganize: "Organização",
    manualOrganizeText: "Crie novas colunas e arraste seus arquivos para organizá-los. Você pode mover itens entre colunas e renomeá-las conforme necessário.",
    manualAutoCrop: "Recorte de IA",
    manualAutoCropText: "Selecione as colunas desejadas e use o ícone de 'Recorte Automático' no topo. A IA identificará o documento e removerá fundos desnecessários.",
    manualEditor: "Editor Profissional",
    manualEditorText: "Clique no ícone de lupa ou 'Editar' em qualquer imagem para abrir o editor. Nele você pode ajustar os 4 cantos para corrigir a perspectiva (Efeito Scanner).",
    manualPdfTools: "Ferramentas de PDF",
    manualPdfToolsText: "Clique em arquivos PDF para reordenar páginas, excluir folhas específicas ou dividir um PDF em vários arquivos menores.",
    manualSettings: "Configurações Avançadas",
    manualSettingsText: "Ative 'Compress' para reduzir o peso do PDF final ou 'OCR AI' para tornar o texto das imagens pesquisável dentro do documento."
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset to Original",
    restore: "Restore Batch",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    autoCropBatch: "Auto Crop (Sel.)",
    applyCrop: "Crop Image",
    manualCrop: "Manual Crop",
    cropInstructions: "Draw an area to crop. Drag edges to adjust.",
    processing: "Processing...",
    imageTools: "Image Tools",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    zoomReset: "Reset Zoom",
    backToGrid: "Back to Grid",
    viewPage: "View Page",
    nextPage: "Next",
    prevPage: "Previous",
    batchProcessError: "Error processing some images.",
    rightsReserved: "All rights reserved",
    supportLink: "Click Here for support",
    footerQuote: '"And let us not grow weary of doing good, for in due season we will reap" — Galatians 6:9',
    brightness: "Brightness",
    contrast: "Contrast",
    adjustHelp: "Adjust contrast to help with background removal.",
    applyAdjustments: "Apply Adjustments",
    updateAvailable: "New version available",
    updateNow: "Update",
    addPages: "Add Pages",
    splitPdf: "Split PDF",
    splitIntervals: "Page Ranges",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Split and Download",
    splitInvalid: "Invalid range. Use formats like 1-3 or 5.",
    comingSoon: "Coming soon: Document Scanning and PDF Files Rotation",
    useOCR: "OCR (Searchable Text)",
    ocrWarning: "OCR makes the process much slower",
    ocrProcessing: "Recognizing text (OCR)...",
    compressPdf: "PDF Compression",
    about: "About",
    aboutTitle: "About Αρχή PDF",
    developedBy: "Created and developed by L. Stivan and H. Cordeiro",
    openSourceLicenses: "Open Source Licenses",
    version: "Version",
    manualTitle: "User Manual",
    manualIntro: "Welcome to Αρχή PDF. Here are the main features:",
    manualOrganize: "Organization",
    manualOrganizeText: "Create new columns and drag your files to organize them. You can move items between columns and rename them as needed.",
    manualAutoCrop: "AI Crop",
    manualAutoCropText: "Select the desired columns and use the 'Auto Crop' icon at the top. The AI will identify the document and remove unnecessary backgrounds.",
    manualEditor: "Professional Editor",
    manualEditorText: "Click on the search icon or 'Edit' on any image to open the editor. There you can adjust the 4 corners to correct the perspective (Scanner Effect).",
    manualPdfTools: "PDF Tools",
    manualPdfToolsText: "Click on PDF files to reorder pages, delete specific sheets, or split a PDF into several smaller files.",
    manualSettings: "Advanced Settings",
    manualSettingsText: "Enable 'Compress' to reduce final PDF size or 'OCR AI' to make image text searchable within the document."
  },
  'es': {
    selectAll: "Seleccionar todo",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar como grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastre o añada",
    dropHere: "Suelte los archivos aquí",
    addFiles: "Añadir archivos",
    edit: "Editar",
    editorTitle: "Editor de imágenes",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Rehacer",
    reset: "Restablecer original",
    restore: "Restaurar lote",
    cancel: "Cancelar",
    confirm: "Confirmar edición",
    removeBg: "Eliminar fondo",
    autoCropBatch: "Recorte automático (Sel.)",
    applyCrop: "Recortar imagen",
    manualCrop: "Recorte manual",
    cropInstructions: "Dibuje un área para recortar. Arrastre los bordes para ajustar.",
    processing: "Procesando...",
    imageTools: "Herramientas de imagen",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de descargas predeterminada.",
    autoSort: "Orden automático",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas con éxito",
    sortError: "Error al ordenar páginas",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    zoomReset: "Restablecer zoom",
    backToGrid: "Volver a la cuadrícula",
    viewPage: "Ver página",
    nextPage: "Siguiente",
    prevPage: "Anterior",
    batchProcessError: "Error al procesar algunas imágenes.",
    rightsReserved: "Todos los derechos reservados",
    supportLink: "Haga clic aquí para obtener ayuda",
    footerQuote: '"Y no nos cansemos de hacer el bien, pues a su tempo segaremos" — Gálatas 6:9',
    brightness: "Brillo",
    contrast: "Contraste",
    adjustHelp: "Ajuste el contraste para ayudar a eliminar el fondo.",
    applyAdjustments: "Aplicar ajustes",
    updateAvailable: "Nueva versión disponible",
    updateNow: "Atualizar",
    addPages: "Añadir páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Rangos de página",
    splitPlaceholder: "Ej: 1-3, 5, 8-10",
    splitAction: "Dividir y descargar",
    splitInvalid: "Rango inválido. Use formatos como 1-3 o 5.",
    comingSoon: "Próximamente: Digitalización (Scanner) y rotação de PDF.",
    useOCR: "OCR (Texto buscable)",
    ocrWarning: "El OCR hace que el proceso sea mucho más lento",
    ocrProcessing: "Reconocimiento de texto (OCR)...",
    compressPdf: "Compresión de PDF",
    about: "Acerca de",
    aboutTitle: "Acerca de Αρχή PDF",
    developedBy: "Creado y desarrollado por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versión",
    manualTitle: "Manual de Usuario",
    manualIntro: "Bienvenido a Αρχή PDF. Estas son las características principales:",
    manualOrganize: "Organización",
    manualOrganizeText: "Cree nuevas columnas y arrastre sus archivos para organizarlos. Puede mover elementos entre columnas y renombrarlos según sea necesario.",
    manualAutoCrop: "Recorte de IA",
    manualAutoCropText: "Seleccione las columnas deseadas y use el icono de 'Recorte automático' en la parte superior. La IA identificará el documento y eliminará fondos innecesarios.",
    manualEditor: "Editor Profesional",
    manualEditorText: "Haga clic en el icono de lupa o 'Editar' en cualquier imagen para abrir el editor. Allí puede ajustar las 4 esquinas para corregir la perspectiva (Efecto Escáner).",
    manualPdfTools: "Herramientas PDF",
    manualPdfToolsText: "Haga clic en los archivos PDF para reordenar páginas, eliminar hojas específicas o dividir un PDF en varios archivos más pequeños.",
    manualSettings: "Ajustes Avanzados",
    manualSettingsText: "Habilite 'Compress' para reducir el tamaño del PDF final o 'OCR AI' para que el texto de la imagen sea buscable dentro del documento."
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Καθαρισμός όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε τα αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επαναφορά",
    reset: "Επαναφορά στο αρχικό",
    restore: "Επαναφορά παρτίδας",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση επεξεργασίας",
    removeBg: "Αφαίρεση φόντου",
    autoCropBatch: "Αυτόματη περικοπή (Επιλ.)",
    applyCrop: "Περικοπή εικόνας",
    manualCrop: "Χειροκίνητη περικοπή",
    cropInstructions: "Σχεδιάστε μια περιοχή για περικοπή. Σύρετε τις άκρες για προσαρμογή.",
    processing: "Επεξεργασία...",
    imageTools: "Εργαλεία εικόνας",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Τα έγγραφα αποθηκεύτηκαν",
    docSaveError: "Σφάλμα κατά την αποθήκευση εγγράφων",
    openFolder: "Εμφάνιση φακέλου προορισμού",
    folderInfo: "Τα αρχεία αποθηκεύονται στον προεπιλεγμένο φάκελο λήψεων.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Οι σελίδες ταξινομήθηκαν με επιτυχία",
    sortError: "Σφάλμα κατά την ταξινόμηση σελίδων",
    zoomIn: "Μεγέθυνση",
    zoomOut: "Σμίκρυνση",
    zoomReset: "Επαναφορά ζουμ",
    eUndo: "Αναίρεση",
    eRedo: "Επαναφορά",
    eReset: "Επαναφορά",
    backToGrid: "Επιστροφή στο πλέγμα",
    viewPage: "Προβολή σελίδας",
    nextPage: "Επόμενο",
    prevPage: "Προηγούμενο",
    batchProcessError: "Σφάλμα κατά την επεξεργασία ορισμένων εικόνων.",
    rightsReserved: "Με επιφύλαξη παντός δικαιώματος",
    supportLink: "Κάντε κλικ εδώ για υποστήριξη",
    footerQuote: '"Και ας μην αποκάμουμε κάνοντας το καλό, γιατί στον δικό του καιρό θα θερίσουμε" — Γαλάτας 6:9',
    brightness: "Φωτεινότητα",
    contrast: "Αντίθεση",
    adjustHelp: "Προσαρμόστε την αντίθεση για να βοηθήσετε στην αφαίρεση του φόντου.",
    applyAdjustments: "Εφαρμογή προσαρμογών",
    updateAvailable: "Νέα έκδοση διαθέσιμη",
    updateNow: "Ενημέρωση",
    addPages: "Προσθήκη σελίδων",
    splitPdf: "Διαίρεση PDF",
    splitIntervals: "Εύρος σελίδων",
    splitPlaceholder: "Πχ: 1-3, 5, 8-10",
    splitAction: "Διαίρεση και λήψη",
    splitInvalid: "Μη έγκυρο εύρος. Χρησιμοποιήστε μορφές όπως 1-3 ή 5.",
    comingSoon: "Σύντομα κοντά σας: Σάρωση εγγράφων.",
    useOCR: "OCR (Αναζητήσιμο κείμενο)",
    ocrWarning: "Το OCR καθυστερεί σημαντικά τη διαδικασία",
    ocrProcessing: "Αναγνώριση κειμένου (OCR)...",
    compressPdf: "Συμπίεση PDF",
    about: "Σχετικά",
    aboutTitle: "Σχετικά με το Αρχή PDF",
    developedBy: "Δημιουργήθηκε από τους L. Stivan και H. Cordeiro",
    openSourceLicenses: "Άδειες ανοιχτού κώδικα",
    version: "Έκδοση",
    manualTitle: "Εγχειρίδιο Χρήστη",
    manualIntro: "Καλώς ήρθατε στο Αρχή PDF. Εδώ είναι τα κύρια χαρακτηριστικά:",
    manualOrganize: "Οργάνωση",
    manualOrganizeText: "Δημιουργήστε νέες στήλες και σύρετε τα αρχεία σας για να τα οργανώσετε. Μπορείτε να μετακινήσετε στοιχεία μεταξύ στηλών και να τα μετονομάσετε όπως απαιτείται.",
    manualAutoCrop: "AI Περικοπή",
    manualAutoCropText: "Επιλέξτε τις επιθυμητές στήλες και χρησιμοποιήστε το εικονίδιο 'Αυτόματη Περικοπή' στο πάνω μέρος. Η AI θα αναγνωρίσει το έγγραφο και θα αφαιρέσει τα περιττά φόντα.",
    manualEditor: "Επαγγελματικός Επεξεργαστής",
    manualEditorText: "Κάντε κλικ στο εικονίδιο αναζήτησης ή στο 'Επεξεργασία' σε οποιαδήποτε εικόνα για να ανοίξετε τον επεξεργαστή. Εκεί μπορείτε να προσαρμόσετε τις 4 γωνίες για να διορθώσετε την προοπτική.",
    manualPdfTools: "Εργαλεία PDF",
    manualPdfToolsText: "Κάντε κλικ στα αρχεία PDF για να αναδιατάξετε σελίδες, να διαγράψετε συγκεκριμένα φύλλα ή να χωρίσετε ένα PDF σε πολλά μικρότερα αρχεία.",
    manualSettings: "Προηγμένες Ρυθμίσεις",
    manualSettingsText: "Ενεργοποιήστε το 'Compress' για να μειώσετε το τελικό μέγεθος PDF ή το 'OCR AI' για να κάνετε το κείμενο της εικόνας αναζητήσιμο μέσα στο έγγραφο."
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה\"כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס למקור",
    restore: "שחזר אצווה",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    autoCropBatch: "חיתוך אוטומטי (נבחרים)",
    applyCrop: "חתוך תמונה",
    manualCrop: "חיתוך ידני",
    cropInstructions: "צייר אזור לחיתוך. גרור קצוות להתאמה.",
    processing: "מעבד...",
    imageTools: "כלי תמונה",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך/ים נשמרו",
    docSaveError: "שגיאה בשמירת המסמך/ים",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות המוגדרת כברירת מחדל.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "העמודים מוינו בהצלחה",
    sortError: "שגיאה במיון העמודים",
    zoomIn: "התקרב",
    zoomOut: "התרחק",
    zoomReset: "אפס זום",
    backToGrid: "חזור לרשת",
    viewPage: "צפה בעמוד",
    nextPage: "הבא",
    prevPage: "הקודם",
    batchProcessError: "שגיאה בעיבוד חלק מהתמונות.",
    rightsReserved: "כל הזכויות שמורות",
    supportLink: "לחץ כאן לתמיכה",
    footerQuote: "\"ואל נלאה מעשות הטוב, כי בעתו נקצר אם לא נרפה\" — גלטיים ו:ט",
    brightness: "בהירות",
    contrast: "ניגודיות",
    adjustHelp: "כוון ניגודיות כדי לסייע בהסרת הרקע.",
    applyAdjustments: "החל התאמות",
    updateAvailable: "גרסה חדשה זמינה",
    updateNow: "עדכן",
    addPages: "הוסף עמודים",
    splitPdf: "פצל PDF",
    splitIntervals: "טווחי עמודים",
    splitPlaceholder: "למשל: 1-3, 5, 8-10",
    splitAction: "פצל והורד",
    splitInvalid: "טווח לא תקין. השתמש בפורמטים כמו 1-3 או 5.",
    comingSoon: "בבקרוב: סריקת מסמכים.",
    useOCR: "OCR (טקסט שניתן לחיפוש)",
    ocrWarning: "OCR הופך את התהליך לאיטי משמעותית",
    ocrProcessing: "מזהה טקסט (OCR)...",
    compressPdf: "דחיסת PDF",
    about: "אודות",
    aboutTitle: "אודות Αρχή PDF",
    developedBy: "נוצר ופותח על ידי L. Stivan ו-H. Cordeiro",
    openSourceLicenses: "רישיונות קוד פתוח",
    version: "גרסה",
    manualTitle: "מדריך למשתמש",
    manualIntro: "ברוכים הבאים ל-Αρχή PDF. להלן התכונות העיקריות:",
    manualOrganize: "ארגון",
    manualOrganizeText: "צור עמודות חדשות וגרור את הקבצים שלך כדי לארגן אותם. אתה יכול להעביר פריטים בין עמודות ולשנות את שמם לפי הצורך.",
    manualAutoCrop: "חיתוך בינה מלאכותית",
    manualAutoCropText: "בחר את העמודות הרצויות והשתמש בסמל 'חיתוך אוטומטי' למעלה. הבינה המלאכותית תזהה את המסמך ותסיר רקעים מיותרים.",
    manualEditor: "עורך מקצועי",
    manualEditorText: "לחץ על סמל החיפוש או 'ערוך' בכל תמונה כדי לפתוח את העורך. שם תוכל להתאים את 4 הפינות כדי לתקן את הפרספקטיבה.",
    manualPdfTools: "כלי PDF",
    manualPdfToolsText: "לחץ על קבצי PDF כדי לשנות את סדר העמודים, למחוק גיליונות ספציפיים או לפצל PDF למספר קבצים קטנים יותר.",
    manualSettings: "הגדרות מתקדמות",
    manualSettingsText: "אפשר את 'Compress' כדי להקטין את גודל ה-PDF הסופי או 'OCR AI' כדי להפוך טקסט בתמונה לניתן לחיפוש בתוך המסמך."
  }
};
