
import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: false,
  saveInGroup: false,
  useOCR: false,
  compressPdf: true,
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar Original",
    restore: "Restaurar Lote",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    autoCropBatch: "Recorte Automático",
    applyCrop: "Recortar Imagem",
    manualCrop: "Recorte Manual",
    cropInstructions: "Desenhe uma área para recortar. Arraste as bordas para ajustar.",
    processing: "Processando...",
    imageTools: "Ajustes de Imagem",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas",
    zoomIn: "Aumentar Zoom",
    zoomOut: "Diminuir Zoom",
    zoomReset: "Restaurar Zoom",
    eUndo: "Desfazer",
    eRedo: "Refazer",
    eReset: "Reset",
    backToGrid: "Voltar para Grade",
    viewPage: "Visualizar Página",
    nextPage: "Próxima",
    prevPage: "Anterior",
    batchProcessError: "Erro ao processar algumas imagens.",
    rightsReserved: "Todos os direitos reservados",
    supportLink: "Clique Aqui para obter suporte",
    footerQuote: '"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos" — Gálatas 6:9',
    brightness: "Brilho",
    contrast: "Contraste",
    adjustHelp: "Ajuste o contraste para facilitar a remoção do fundo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nova versão disponível",
    updateNow: "Atualizar",
    addPages: "Adicionar Páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Dividir e Baixar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 ou 5.",
    comingSoon: "Em breve: Digitalização (Scanner).",
    useOCR: "OCR",
    ocrWarning: "O OCR torna o processo muito mais lento",
    ocrProcessing: "Reconhecendo texto (OCR)...",
    compressPdf: "Compressão de PDF",
    about: "Sobre",
    aboutTitle: "Sobre Αρχή PDF",
    developedBy: "Criado e desenvolvido por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versão",
    manualTitle: "Manual do Usuário",
    manualIntro: "Bem-vindo ao Αρχή PDF v2.6. Aqui estão as principais funcionalidades detalhadas:",
    manualOrganize: "Organização e Colunas",
    manualOrganizeText: "Organize seus documentos criando colunas. Você pode renomear cada PDF final, mover páginas entre documentos via Drag and Drop e selecionar quais deseja exportar.",
    manualAutoCrop: "Recorte Inteligente",
    manualAutoCropText: "Ao clicar em 'Recorte Automático', nossa IA detecta as bordas do papel, remove o fundo e corrige a perspectiva, criando um efeito de scanner profissional instantâneo.",
    manualEditor: "Edição Profissional de Imagem",
    manualEditorText: "No editor você tem controle total: Rotação de imagem (90° em 90°), ajuste fino de Brilho e Contraste para clareza, e Recorte Manual de precisão para documentos complexos.",
    manualPdfTools: "Gerenciamento de PDF",
    manualPdfToolsText: "Adicione páginas a PDFs existentes, reordene a sequência das folhas, exclua páginas indesejadas ou divida um PDF grande em vários arquivos menores por intervalos.",
    manualSettings: "Configurações de IA",
    manualSettingsText: "Utilize 'Compress' para gerar arquivos leves e otimizados para envio. Ative 'OCR AI' para que o texto das suas imagens se torne selecionável e pesquisável no PDF final.",
    pdfEditHighlight: "Novidade: Edição Completa!",
    pdfEditHighlightText: "Agora você pode recortar páginas de PDF, girar e ajustar a perspectiva individualmente para cada folha!"
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset to Original",
    restore: "Restore Batch",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    autoCropBatch: "Auto Crop",
    applyCrop: "Crop Image",
    manualCrop: "Manual Crop",
    cropInstructions: "Draw an area to crop. Drag edges to adjust.",
    processing: "Processing...",
    imageTools: "Image Tools",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    zoomReset: "Reset Zoom",
    backToGrid: "Back to Grid",
    viewPage: "View Page",
    nextPage: "Next",
    prevPage: "Previous",
    batchProcessError: "Error processing some images.",
    rightsReserved: "All rights reserved",
    supportLink: "Click Here for support",
    footerQuote: '"And let us not grow weary of doing good, for in due season we will reap" — Galatians 6:9',
    brightness: "Brightness",
    contrast: "Contrast",
    adjustHelp: "Adjust contrast to help with background removal.",
    applyAdjustments: "Apply Adjustments",
    updateAvailable: "New version available",
    updateNow: "Update",
    addPages: "Add Pages",
    splitPdf: "Split PDF",
    splitIntervals: "Page Ranges",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Split and Download",
    splitInvalid: "Invalid range. Use formats like 1-3 or 5.",
    comingSoon: "Coming soon: Document Scanning",
    useOCR: "OCR (Searchable Text)",
    ocrWarning: "OCR makes the process much slower",
    ocrProcessing: "Recognizing text (OCR)...",
    compressPdf: "PDF Compression",
    about: "About",
    aboutTitle: "About Αρχή PDF",
    developedBy: "Created and developed by L. Stivan and H. Cordeiro",
    openSourceLicenses: "Open Source Licenses",
    version: "Version",
    manualTitle: "User Manual",
    manualIntro: "Welcome to Αρχή PDF v2.6. Here are the main features detailed:",
    manualOrganize: "Organization and Columns",
    manualOrganizeText: "Organize your documents by creating columns. You can rename each final PDF, move pages between documents via Drag and Drop and select which ones you want to export.",
    manualAutoCrop: "OpenCV Smart Crop",
    manualAutoCropText: "When clicking 'Auto Crop', our AI detects the edges of the paper, removes the background and corrects the perspective, creating an instant professional scanner effect.",
    manualEditor: "Professional Image Editing",
    manualEditorText: "In the editor you have full control: Image rotation (90° by 90°), fine adjustment of Brightness and Contrast for clarity, and precision Manual Crop for complex documents.",
    manualPdfTools: "PDF Management",
    manualPdfToolsText: "Add pages to existing PDFs, reorder the page sequence, delete unwanted pages or split a large PDF into several smaller files by ranges.",
    manualSettings: "AI Advanced Settings",
    manualSettingsText: "Use 'Compress' to generate light and optimized files. Enable 'OCR AI' so that the text of your images becomes selectable and searchable in the final PDF.",
    pdfEditHighlight: "New: Full Editing!",
    pdfEditHighlightText: "Now you can crop PDF pages, rotate and adjust perspective individually for each sheet!"
  },
  'es': {
    selectAll: "Seleccionar todo",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar como grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastre o añada",
    dropHere: "Suelte los archivos aquí",
    addFiles: "Añadir archivos",
    edit: "Editar",
    editorTitle: "Editor de imágenes",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Refacer",
    reset: "Restablecer original",
    restore: "Restaurar lote",
    cancel: "Cancelar",
    confirm: "Confirmar edición",
    removeBg: "Eliminar fondo",
    autoCropBatch: "Recorte automático",
    applyCrop: "Recortar imagen",
    manualCrop: "Recorte manual",
    cropInstructions: "Dibuje un área para recortar. Arrastre los bordes para ajustar.",
    processing: "Procesando...",
    imageTools: "Herramientas de imagen",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de descargas predeterminada.",
    autoSort: "Orden automático",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas con éxito",
    sortError: "Error al ordenar páginas",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    zoomReset: "Restablecer zoom",
    backToGrid: "Volver a la cuadrícula",
    viewPage: "Ver página",
    nextPage: "Siguiente",
    prevPage: "Anterior",
    batchProcessError: "Error al procesar algunas imágenes.",
    rightsReserved: "Todos los derechos reservados",
    supportLink: "Haga clic aquí para obtener ayuda",
    footerQuote: '"Y no nos cansemos de hacer el bien, pues a su tempo segaremos" — Gálatas 6:9',
    brightness: "Brillo",
    contrast: "Contraste",
    adjustHelp: "Ajuste el contraste para ayudar a eliminar el fondo.",
    applyAdjustments: "Aplicar ajustes",
    updateAvailable: "Nueva versión disponible",
    updateNow: "Atualizar",
    addPages: "Añadir páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Rangos de página",
    splitPlaceholder: "Ej: 1-3, 5, 8-10",
    splitAction: "Dividir y descargar",
    splitInvalid: "Rango inválido. Use formatos como 1-3 o 5.",
    comingSoon: "Próximamente: Digitalización (Scanner).",
    useOCR: "OCR (Texto buscable)",
    ocrWarning: "El OCR hace que el proceso sea mucho más lento",
    ocrProcessing: "Reconocimiento de texto (OCR)...",
    compressPdf: "Compresión de PDF",
    about: "Acerca de",
    aboutTitle: "Acerca de Αρχή PDF",
    developedBy: "Creado y desarrollado por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versión",
    manualTitle: "Manual de Usuario",
    manualIntro: "Bienvenido a Αρχή PDF v2.6. Aquí están las principales funcionalidades detalladas:",
    manualOrganize: "Organización y Columnas",
    manualOrganizeText: "Organice sus documentos creando columnas. Puede renombrar cada PDF final, mover páginas entre documentos y seleccionar cuáles exportar.",
    manualAutoCrop: "Recorte Inteligente OpenCV",
    manualAutoCropText: "Nuestra IA detecta los bordes del papel, elimina el fondo y corrige la perspectiva, creando un efecto de escáner profesional al instante.",
    manualEditor: "Edición Profesional de Imagen",
    manualEditorText: "En el editor tienes control total: Rotación de imagen (90°), ajuste de Brillo y Contraste para mayor claridad, y Recorte Manual de precisión.",
    manualPdfTools: "Gestión de PDF",
    manualPdfToolsText: "Agregue páginas a PDFs existentes, reordene la secuencia, elimine páginas no deseadas o divida un PDF grande en varios archivos.",
    manualSettings: "Ajustes de IA",
    manualSettingsText: "Utilice 'Compress' para generar archivos ligeros. Active 'OCR AI' para que el texto de sus imágenes sea buscable en el PDF final.",
    pdfEditHighlight: "Nuevo: ¡Edición Completa!",
    pdfEditHighlightText: "¡Ahora puedes recortar páginas de PDF, girar y ajustar la perspectiva individualmente para cada hoja!"
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Καθαρισμός όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε τα αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επαναφορά",
    reset: "Επαναφορά στο αρχικό",
    restore: "Επαναφορά παρτίδας",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση επεξεργασίας",
    removeBg: "Αφαίρεση φόντου",
    autoCropBatch: "Αυτόματη περικοπή",
    applyCrop: "Περικοπή εικόνας",
    manualCrop: "Χειροκίνητη περικοπή",
    cropInstructions: "Σχεδιάστε μια περιοχή για περικοπή. Σύρετε τις άκρες για προσαρμογή.",
    processing: "Επεξεργασία...",
    imageTools: "Εργαλεία εικόνας",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Τα έγγραφα αποθηκεύτηκαν",
    docSaveError: "Σφάλμα κατά την αποθήκευση εγγράφων",
    openFolder: "Εμφάνιση φακέλου προορισμού",
    folderInfo: "Τα αρχεία αποθηκεύονται στον προεπιλεγμένο φάκελο λήψεων.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Οι σελίδες ταξινομήθηκαν με επιτυχία",
    sortError: "Σφάλμα κατά την ταξινόμηση σελίδων",
    zoomIn: "Μεγέθυνση",
    zoomOut: "Σμίκρυνση",
    zoomReset: "Επαναφορά ζουμ",
    eUndo: "Αναίρεση",
    eRedo: "Επαναφορά",
    eReset: "Επαναφορά",
    backToGrid: "Επιστροφή στο πλέγμα",
    viewPage: "Προβολή σελίδας",
    nextPage: "Επόμενο",
    prevPage: "Προηγούμενο",
    batchProcessError: "Σφάλμα κατά την επεξεργασία ορισμένων εικόνων.",
    rightsReserved: "Με επιφύλαξη παντός δικαιώματος",
    supportLink: "Κάντε κλικ εδώ για υποστήριξη",
    footerQuote: '"Και ας μην αποκάμουμε κάνοντας το καλό, γιατί στον δικό του καιρό θα θερίσουμε" — Γαλάτας 6:9',
    brightness: "Φωτεινότητα",
    contrast: "Αντίθεση",
    adjustHelp: "Προσαρμόστε την αντίθεση για να βοηθήσετε στην αφαίρεση του φόντου.",
    applyAdjustments: "Εφαρμογή προσαρμογών",
    updateAvailable: "Νέα έκδοση διαθέσιμη",
    updateNow: "Ενημέρωση",
    addPages: "Προσθήκη σελίδων",
    splitPdf: "Διαίρεση PDF",
    splitIntervals: "Εύρος σελίδων",
    splitPlaceholder: "Πχ: 1-3, 5, 8-10",
    splitAction: "Διαίρεση και λήψη",
    splitInvalid: "Μη έγκυρο εύρος. Χρησιμοποιήστε μορφές όπως 1-3 ή 5.",
    comingSoon: "Σύντομα κοντά σας: Σάρωση εγγράφων.",
    useOCR: "OCR (Αναζητήσιμο κείμενο)",
    ocrWarning: "Το OCR καθυστερεί σημαντικά τη διαδικασία",
    ocrProcessing: "Αναγνώριση κειμένου (OCR)...",
    compressPdf: "Συμπίεση PDF",
    about: "Σχετικά",
    aboutTitle: "Σχετικά με το Αρχή PDF",
    developedBy: "Δημιουργήθηκε από τους L. Stivan και H. Cordeiro",
    openSourceLicenses: "Άδειες ανοιχτού κώδικα",
    version: "Έκδοση",
    manualTitle: "Εγχειρίδιο Χρήστη",
    manualIntro: "Καλώς ήρθατε στο Αρχή PDF v2.6. Εδώ είναι τα κύρια χαρακτηριστικά:",
    manualOrganize: "Οργάνωση και Στήλες",
    manualOrganizeText: "Οργανώστε τα έγγραφά σας δημιουργώντας στήλες. Μπορείτε να μετονομάσετε κάθε PDF, να μετακινήσετε σελίδες και να επιλέξετε ποιες θα εξαγάγετε.",
    manualAutoCrop: "Έξυπνη Περικοπή OpenCV",
    manualAutoCropText: "Η AI μας ανιχνεύει τις άκρες του χαρτιού, αφαιρεί το φόντο και διορθώνει την προοπτική, δημιουργώντας ένα εφέ επαγγελματικού σαρωτή.",
    manualEditor: "Επαγγελματική Επεξεργασία Εικόνας",
    manualEditorText: "Στον επεξεργαστή έχετε πλήρη έλεγχο: Περιστροφή εικόνας (90°), ρύθμιση Φωτεινότητας και Αντίθεσης και Χειροκίνητη Περικοπή ακριβείας.",
    manualPdfTools: "Διαχείριση PDF",
    manualPdfToolsText: "Προσθέστε σελίδες σε υπάρχοντα PDF, αναδιατάξτε τη σειρά, διαγράψτε σελίδες ή χωρίστε ένα PDF σε πολλά αρχεία.",
    manualSettings: "Ρυθμίσεις AI",
    manualSettingsText: "Χρησιμοποιήστε το 'Compress' για ελαφριά αρχεία. Ενεργοποιήστε το 'OCR AI' για αναζητήσιμο κείμενο στο τελικό PDF.",
    pdfEditHighlight: "Νέα: Πλήρης Επεξεργασία!",
    pdfEditHighlightText: "Τώρα μπορείτε να περικόψετε σελίδες PDF, να τις περιστρέψετε και να προσαρμόσετε την προοπτική μεμονωμένα για κάθε φύλλο!"
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה\"כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס למקור",
    restore: "שחזר אצווה",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    autoCropBatch: "חיתוך אוטומטי",
    applyCrop: "חתוך תמונה",
    manualCrop: "חיתוך ידני",
    cropInstructions: "צייר אזור לחיתוך. גרור קצוות להתאמה.",
    processing: "מעבד...",
    imageTools: "כלי תמונה",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך/ים נשמרו",
    docSaveError: "שגיאה בשמירת המסמך/ים",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות המוגדרת כברירת מחדל.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "העמודים מוינו בהצלחה",
    sortError: "שגיאה במיון העמודים",
    zoomIn: "התקרב",
    zoomOut: "התרחק",
    zoomReset: "אפס זום",
    backToGrid: "חזור לרשת",
    viewPage: "צפה בעמוד",
    nextPage: "הבא",
    prevPage: "הקודם",
    batchProcessError: "שגיאה בעיבוד חלק מהתמונות.",
    rightsReserved: "כל הזכויות שמורות",
    supportLink: "לחץ כאן לתמיכה",
    footerQuote: "\"ואל נלאה מעשות הטוב, כי בעתו נקצר אם לא נרפה\" — גלטיים ו:ט",
    brightness: "בהירות",
    contrast: "ניגודיות",
    adjustHelp: "כוון ניגודיות כדי לסייע בהסרת הרקע.",
    applyAdjustments: "החל התאמות",
    updateAvailable: "גרסה חדשה זמינה",
    updateNow: "עדכן",
    addPages: "הוסף עמודים",
    splitPdf: "פצל PDF",
    splitIntervals: "טווחי עמודים",
    splitPlaceholder: "למשל: 1-3, 5, 8-10",
    splitAction: "פצל והורד",
    splitInvalid: "טווח לא תקין. השתמש בפורמטים כמו 1-3 או 5.",
    comingSoon: "בבקרוב: סריקת מסמכים.",
    useOCR: "OCR (טקסט שניתן לחיפוש)",
    ocrWarning: "OCR הופך את התהליך לאיטי משמעותית",
    ocrProcessing: "מזהה טקסט (OCR)...",
    compressPdf: "דחיסת PDF",
    about: "אודות",
    aboutTitle: "אודות Αρχή PDF",
    developedBy: "נוצר ופותח על ידי L. Stivan ו-H. Cordeiro",
    openSourceLicenses: "רישיונות קוד פתוח",
    version: "גרסה",
    manualTitle: "מדריך למשתמש",
    manualIntro: "ברוכים הבאים ל-Αρχή PDF v2.6. להלן התכונות העיקריות:",
    manualOrganize: "ארגון ועמודות",
    manualOrganizeText: "ארגן את המסמכים שלך על ידי יצירת עמודות. אתה יכול לשנות את השם של cada PDF, להעביר עמודים ולבחור מה לייצא.",
    manualAutoCrop: "חיתוך חכם OpenCV",
    manualAutoCropText: "הבינה המלאכותית שלנו מזהה את קצוות הנייר, מסירה את הרקע ומתקנת את הפרספקטיבה, ויוצרת אפקט סורק מקצועי מיידי.",
    manualEditor: "עריכת תמונה מקצועית",
    manualEditorText: "בעורך יש לך שליטה מלאה: סיבוב תמונה (90°), כוונון בהירות וניגודיות לבהירות, וחיתוך ידני מדויק.",
    manualPdfTools: "ניהול PDF",
    manualPdfToolsText: "הוסף עמודים ל-PDF קיימים, שנה את סדר העמודים, מחק עמודים לא רצויים או פצל PDF לקבצים מרובים.",
    manualSettings: "הגדרות בינה מלאלאכותית",
    manualSettingsText: "השתמש ב-'Compress' לקבצים קלים. אפשר 'OCR AI' כדי שהטקסט בתמונות שלך יהפוך לניתן לחיפוש ב-PDF הסופי.",
    pdfEditHighlight: "חדש: עריכה מלאה!",
    pdfEditHighlightText: "כעת תוכלו לחתוך עמודי PDF, לסובב ולהתאים פרספקטיבה בנפרד לכל גיליון!"
  }
};
