
import { Language } from './types';

export const SUPPORTED_FORMATS = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg', 'application/pdf'];

export const INITIAL_SETTINGS = {
  convertToPdf: true,
  saveSeparately: true,
  saveInGroup: false,
  useOCR: true,
  compressPdf: true,
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    selectAll: "Selecionar todos",
    clearAll: "Limpar todos",
    convertToPdf: "Converter para PDF",
    saveSeparately: "Salvar separado",
    saveInGroup: "Salvar em grupo",
    save: "Salvar",
    saving: "Salvando...",
    total: "Total",
    dragDrop: "Arraste ou adicione",
    dropHere: "Solte os arquivos",
    addFiles: "Adicionar arquivos",
    edit: "Editar",
    editorTitle: "Editor de Imagem",
    pdfEditorTitle: "Editor de PDF",
    undo: "Desfazer",
    redo: "Refazer",
    reset: "Restaurar Original",
    restore: "Restaurar Lote",
    cancel: "Cancelar",
    confirm: "Confirmar Edição",
    removeBg: "Remover Fundo",
    autoCropBatch: "Recorte Automático",
    processing: "Processando...",
    language: "Português do Brasil",
    theme: "Tema",
    deleteDoc: "Excluir documento",
    search: "Visualizar",
    rotate: "Girar",
    page: "Página",
    savePdf: "Salvar PDF",
    loadingPdf: "Carregando PDF...",
    docSaved: "Documento(s) Salvo(s)",
    docSaveError: "Erro ao salvar documento(s)",
    openFolder: "Exibir pasta de destino",
    folderInfo: "Os arquivos foram salvos na sua pasta padrão de Downloads.",
    autoSort: "Ordenar Auto",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas com sucesso",
    sortError: "Erro ao ordenar páginas",
    zoomIn: "Aumentar Zoom",
    zoomOut: "Diminuir Zoom",
    zoomReset: "Restaurar Zoom",
    backToGrid: "Voltar para Grade",
    viewPage: "Visualizar Página",
    nextPage: "Próxima",
    prevPage: "Anterior",
    batchProcessError: "Erro ao processar algumas imagens.",
    rightsReserved: "Todos os direitos reservados",
    supportLink: "Clique Aqui para obter suporte",
    footerQuote: '"E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos" — Gálatas 6:9',
    brightness: "Brilho",
    contrast: "Contraste",
    applyCropError: "Erro ao aplicar recorte.",
    saveError: "Erro ao salvar.",
    rotateError: "Erro ao girar imagem.",
    manualCrop: "Recorte Manual",
    cropInstructions: "Arraste os cantos detectados para ajustar a perspectiva.",
    applyCrop: "Aplicar Recorte",
    imageTools: "Ajustes",
    addText: "Adicionar Texto",
    font: "Fonte",
    color: "Cor",
    size: "Tamanho",
    textPlaceholder: "Digite seu texto...",
    removeText: "Remover Texto",
    initEditorError: "Erro ao inicializar o editor de PDF.",
    renderHighResError: "Erro ao renderizar página em alta resolução.",
    items: "itens",
    cache: "Cache",
    fileRestored: "Arquivo restaurado.",
    newManual: "Novo: Manual v2.8",
    toggleTheme: "Alternar Tema",
    manualClose: "Entendi, vamos começar!",
    close: "Fechar",
    cvLoadError: "OpenCV.js não pôde ser carregado.",
    pdfjsLoadError: "PDF.js não carregado.",
    blobError: "Falha ao criar Blob.",
    canvasContextError: "Não foi possível obter o contexto do canvas.",
    pdfLibLoadError: "Biblioteca de PDF não carregada.",
    cropSuccess: "Recorte concluído!",
    dropError: "Erro ao soltar arquivo.",
    itemDropError: "Erro ao soltar item.",
    appTitle: "PDF Temp - Editor de Documentos",
    appDescription: "Editor de documentos PDF e imagens local e seguro.",
    noDocFound: "Nenhum documento identificado.",
    changelog_v2_8: "v2.8 - NOVO: Ferramenta de Texto no Editor, Colagem de imagens (CTRL+V) no Kanban e melhorias de UX",
    changelog_v2_7: "v2.7 - NOVO: Rotação de PDF, Recorte de PDF, melhorias visuais e correção de bugs menores",
    changelog_v2_6: "v2.6 - Ferramentas avançadas de Edição de PDF, Recorte de Perspectiva e correção de bugs",
    changelog_v2_5: "v2.5 - Manual do Usuário interativo e detalhado",
    changelog_v2_4: "v2.4 - Recurso de Compressão de PDF de alta performance",
    changelog_v2_3: "v2.3 - Sistema de Detecção de Atualizações Automáticas",
    adjustHelp: "Ajuste o contraste para facilitar a remoção do fundo.",
    applyAdjustments: "Aplicar Ajustes",
    updateAvailable: "Nova versão disponível",
    updateNow: "Atualizar",
    addPages: "Adicionar Páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Intervalos de Página",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Dividir e Baixar",
    splitInvalid: "Intervalo inválido. Use formatos como 1-3 ou 5.",
    comingSoon: "Em breve: Digitalização (Scanner).",
    useOCR: "OCR",
    ocrWarning: "O OCR torna o processo muito mais lento",
    ocrProcessing: "Reconhecendo texto (OCR)...",
    compressPdf: "Compressão de PDF",
    compress: "Comprimir",
    ocrInfo: "Quando ativado, o PDF será salvo no formato de texto selecionável",
    ocrConfirm: "O processamento de PDF com texto selecionável (OCR) pode ser significativamente mais lento. Deseja ativar?",
    compressHighlight: "Novo: Comprimir arquivos PDF",
    rotateLeft: "Girar Esquerda",
    rotateRight: "Girar Direita",
    recrop: "Recortar Novamente",
    pageShort: "Pág",
    savePdfError: "Erro ao salvar o PDF editado.",
    about: "Sobre",
    aboutTitle: "Sobre Αρχή PDF",
    developedBy: "Criado e desenvolvido por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versão",
    manualTitle: "Manual do Usuário",
    manualIntro: "Bem-vindo ao Αρχή PDF v2.8. Aqui estão as principais funcionalidades detalhadas:",
    manualOrganize: "Organização e Colunas",
    manualOrganizeText: "Organize seus documentos criando colunas. Você pode renomear cada PDF final, mover páginas entre documentos via Drag and Drop, colar imagens da área de transferência (CTRL+V) e selecionar quais deseja exportar.",
    manualAutoCrop: "Recorte Inteligente",
    manualAutoCropText: "Ao clicar em 'Recorte Automático', nossa IA detecta as bordas do papel, remove o fundo e corrige a perspectiva, criando um efeito de scanner profissional instantâneo.",
    manualEditor: "Edição Profissional de Imagem",
    manualEditorText: "No editor você tem controle total: Rotação de imagem (90°), ajuste fino de Brilho e Contraste, Recorte Manual de precisão e nova ferramenta de Texto para anotações personalizáveis.",
    manualPdfTools: "Gerenciamento de PDF",
    manualPdfToolsText: "Adicione páginas a PDFs existentes, reordene a sequência das folhas, exclua páginas indesejadas ou divida um PDF grande em vários arquivos menores por intervalos.",
    manualSettings: "Configurações de IA",
    manualSettingsText: "Utilize 'Compress' para gerar arquivos leves e otimizados para envio. Ative 'OCR AI' para que o texto das suas imagens se torne selecionável e pesquisável no PDF final.",
    pdfEditHighlight: "Novidade: Edição Completa!",
    pdfEditHighlightText: "Agora você pode recortar páginas de PDF, girar e ajustar a perspectiva individualmente para cada folha!"
  },
  'en': {
    selectAll: "Select All",
    clearAll: "Clear All",
    convertToPdf: "Convert to PDF",
    saveSeparately: "Save Separately",
    saveInGroup: "Save as Group",
    save: "Save",
    saving: "Saving...",
    total: "Total",
    dragDrop: "Drag or add",
    dropHere: "Drop files here",
    addFiles: "Add files",
    edit: "Edit",
    editorTitle: "Image Editor",
    pdfEditorTitle: "PDF Editor",
    undo: "Undo",
    redo: "Redo",
    reset: "Reset to Original",
    restore: "Restore Batch",
    cancel: "Cancel",
    confirm: "Confirm Edit",
    removeBg: "Remove Background",
    autoCropBatch: "Auto Crop",
    processing: "Processing...",
    language: "English",
    theme: "Theme",
    deleteDoc: "Delete document",
    search: "Preview",
    rotate: "Rotate",
    page: "Page",
    savePdf: "Save PDF",
    loadingPdf: "Loading PDF...",
    docSaved: "Document(s) Saved",
    docSaveError: "Error saving document(s)",
    openFolder: "Show destination folder",
    folderInfo: "Files are saved to your default Downloads folder.",
    autoSort: "Auto Sort",
    sorting: "Sorting...",
    sortSuccess: "Pages sorted successfully",
    sortError: "Error sorting pages",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    zoomReset: "Reset Zoom",
    backToGrid: "Back to Grid",
    viewPage: "View Page",
    nextPage: "Next",
    prevPage: "Previous",
    batchProcessError: "Error processing some images.",
    rightsReserved: "All rights reserved",
    supportLink: "Click Here for support",
    footerQuote: '"And let us not grow weary of doing good, for in due season we will reap" — Galatians 6:9',
    brightness: "Brightness",
    contrast: "Contrast",
    applyCropError: "Error applying crop.",
    saveError: "Error saving.",
    rotateError: "Error rotating image.",
    manualCrop: "Manual Crop",
    cropInstructions: "Drag the detected corners to adjust the perspective.",
    applyCrop: "Apply Crop",
    imageTools: "Adjustments",
    addText: "Add Text",
    font: "Font",
    color: "Color",
    size: "Size",
    textPlaceholder: "Type your text...",
    removeText: "Remove Text",
    initEditorError: "Error initializing PDF editor.",
    renderHighResError: "Error rendering high-res page.",
    items: "items",
    cache: "Cache",
    fileRestored: "File restored.",
    newManual: "New: Manual v2.8",
    toggleTheme: "Toggle Theme",
    manualClose: "Got it, let's start!",
    close: "Close",
    cvLoadError: "OpenCV.js could not be loaded.",
    pdfjsLoadError: "PDF.js not loaded.",
    blobError: "Blob creation failed.",
    canvasContextError: "Could not get canvas context.",
    pdfLibLoadError: "PDF library not loaded.",
    cropSuccess: "Cropping completed!",
    dropError: "Error dropping file.",
    itemDropError: "Error dropping item.",
    appTitle: "PDF Temp - Document Editor",
    appDescription: "Local and secure PDF and image document editor.",
    noDocFound: "No document identified.",
    changelog_v2_8: "v2.8 - NEW: Text Tool in Editor, Image Pasting (CTRL+V) in Kanban and UX improvements",
    changelog_v2_7: "v2.7 - NEW: PDF Rotation, PDF Cropping, visual improvements and minor bug fixes",
    changelog_v2_6: "v2.6 - Advanced PDF Editing, Perspective Crop tools and bug fixes",
    changelog_v2_5: "v2.5 - Detailed and interactive User Manual",
    changelog_v2_4: "v2.4 - High-performance PDF Compression feature",
    changelog_v2_3: "v2.3 - Automatic Update Detection System",
    adjustHelp: "Adjust contrast to help with background removal.",
    applyAdjustments: "Apply Adjustments",
    updateAvailable: "New version available",
    updateNow: "Update",
    addPages: "Add Pages",
    splitPdf: "Split PDF",
    splitIntervals: "Page Ranges",
    splitPlaceholder: "Ex: 1-3, 5, 8-10",
    splitAction: "Split and Download",
    splitInvalid: "Invalid range. Use formats like 1-3 or 5.",
    comingSoon: "Coming soon: Document Scanning",
    useOCR: "OCR (Searchable Text)",
    ocrWarning: "OCR makes the process much slower",
    ocrProcessing: "Recognizing text (OCR)...",
    compressPdf: "PDF Compression",
    compress: "Compress",
    ocrInfo: "When enabled, the PDF will be saved in selectable text format",
    ocrConfirm: "OCR processing may be significantly slower. Do you want to enable it?",
    compressHighlight: "New: Compress PDF files",
    rotateLeft: "Rotate Left",
    rotateRight: "Rotate Right",
    recrop: "Recrop",
    pageShort: "Page",
    savePdfError: "Error saving edited PDF.",
    about: "About",
    aboutTitle: "About Αρχή PDF",
    developedBy: "Created and developed by L. Stivan and H. Cordeiro",
    openSourceLicenses: "Open Source Licenses",
    version: "Version",
    manualTitle: "User Manual",
    manualIntro: "Welcome to Αρχή PDF v2.8. Here are the main features detailed:",
    manualOrganize: "Organization and Columns",
    manualOrganizeText: "Organize your documents by creating columns. You can rename each final PDF, move pages between documents via Drag and Drop, paste images from the clipboard (CTRL+V) and select which ones you want to export.",
    manualAutoCrop: "OpenCV Smart Crop",
    manualAutoCropText: "When clicking 'Auto Crop', our AI detects the edges of the paper, removes the background and corrects the perspective, creating an instant professional scanner effect.",
    manualEditor: "Professional Image Editing",
    manualEditorText: "In the editor you have full control: Image rotation (90°), fine adjustment of Brightness and Contrast, precision Manual Crop, and a new Text tool for customizable annotations.",
    manualPdfTools: "PDF Management",
    manualPdfToolsText: "Add pages to existing PDFs, reorder the page sequence, delete unwanted pages or split a large PDF into several smaller files by ranges.",
    manualSettings: "AI Advanced Settings",
    manualSettingsText: "Use 'Compress' to generate light and optimized files. Enable 'OCR AI' so that the text of your images becomes selectable and searchable in the final PDF.",
    pdfEditHighlight: "New: Full Editing!",
    pdfEditHighlightText: "Now you can crop PDF pages, rotate and adjust perspective individually for each sheet!"
  },
  'es': {
    selectAll: "Seleccionar todo",
    clearAll: "Limpiar todo",
    convertToPdf: "Convertir a PDF",
    saveSeparately: "Guardar por separado",
    saveInGroup: "Guardar como grupo",
    save: "Guardar",
    saving: "Guardando...",
    total: "Total",
    dragDrop: "Arrastre o añada",
    dropHere: "Suelte los archivos aquí",
    addFiles: "Añadir archivos",
    edit: "Editar",
    editorTitle: "Editor de imágenes",
    pdfEditorTitle: "Editor de PDF",
    undo: "Deshacer",
    redo: "Refacer",
    reset: "Restablecer original",
    restore: "Restaurar lote",
    cancel: "Cancelar",
    confirm: "Confirmar edición",
    removeBg: "Eliminar fondo",
    autoCropBatch: "Recorte automático",
    processing: "Procesando...",
    language: "Español",
    theme: "Tema",
    deleteDoc: "Eliminar documento",
    search: "Vista previa",
    rotate: "Girar",
    page: "Página",
    savePdf: "Guardar PDF",
    loadingPdf: "Cargando PDF...",
    docSaved: "Documento(s) guardado(s)",
    docSaveError: "Error al guardar documento(s)",
    openFolder: "Mostrar carpeta de destino",
    folderInfo: "Los archivos se guardan en su carpeta de descargas predeterminada.",
    autoSort: "Orden automático",
    sorting: "Ordenando...",
    sortSuccess: "Páginas ordenadas con éxito",
    sortError: "Error al ordenar páginas",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    zoomReset: "Restablecer zoom",
    backToGrid: "Volver a la cuadrícula",
    viewPage: "Ver página",
    nextPage: "Siguiente",
    prevPage: "Anterior",
    batchProcessError: "Error al procesar algunas imágenes.",
    rightsReserved: "Todos los derechos reservados",
    supportLink: "Haga clic aquí para obtener ayuda",
    footerQuote: '"Y no nos cansemos de hacer el bien, pues a su tempo segaremos" — Gálatas 6:9',
    brightness: "Brillo",
    contrast: "Contraste",
    applyCropError: "Error al aplicar el recorte.",
    saveError: "Error al guardar.",
    rotateError: "Error al girar la imagen.",
    manualCrop: "Recorte Manual",
    cropInstructions: "Arrastre las esquinas detectadas para ajustar la perspectiva.",
    applyCrop: "Aplicar Recorte",
    imageTools: "Ajustes",
    addText: "Añadir Texto",
    font: "Fuente",
    color: "Color",
    size: "Tamaño",
    textPlaceholder: "Escribe tu texto...",
    removeText: "Eliminar Texto",
    initEditorError: "Error al inicializar el editor de PDF.",
    renderHighResError: "Error al renderizar la página en alta resolución.",
    items: "ítems",
    cache: "Caché",
    fileRestored: "Archivo restaurado.",
    newManual: "Nuevo: Manual v2.8",
    toggleTheme: "Cambiar Tema",
    manualClose: "¡Entendido, empecemos!",
    close: "Cerrar",
    cvLoadError: "OpenCV.js no pudo ser cargado.",
    pdfjsLoadError: "PDF.js no cargado.",
    blobError: "Error al crear el Blob.",
    canvasContextError: "No se pudo obtener el contexto del canvas.",
    pdfLibLoadError: "Biblioteca de PDF no cargada.",
    cropSuccess: "¡Recorte completado!",
    dropError: "Error al soltar el archivo.",
    itemDropError: "Error al soltar el elemento.",
    appTitle: "PDF Temp - Editor de Documentos",
    appDescription: "Editor de documentos PDF e imágenes local y seguro.",
    noDocFound: "No se identificó ningún documento.",
    changelog_v2_8: "v2.8 - NUEVO: Herramienta de Texto en el Editor, Pegado de imágenes (CTRL+V) en Kanban y mejoras de UX",
    changelog_v2_7: "v2.7 - NUEVO: Rotación de PDF, Recorte de PDF, mejoras visuales y corrección de errores menores",
    changelog_v2_6: "v2.6 - Herramientas avanzadas de edición de PDF, recorte de perspectiva y corrección de errores",
    changelog_v2_5: "v2.5 - Manual de usuario interactivo y detallado",
    changelog_v2_4: "v2.4 - Función de compresión de PDF de alto rendimiento",
    changelog_v2_3: "v2.3 - Sistema de detección de actualizaciones automáticas",
    adjustHelp: "Ajuste el contraste para ayudar a eliminar el fondo.",
    applyAdjustments: "Aplicar ajustes",
    updateAvailable: "Nueva versión disponible",
    updateNow: "Atualizar",
    addPages: "Añadir páginas",
    splitPdf: "Dividir PDF",
    splitIntervals: "Rangos de página",
    splitPlaceholder: "Ej: 1-3, 5, 8-10",
    splitAction: "Dividir y descargar",
    splitInvalid: "Rango inválido. Use formatos como 1-3 o 5.",
    comingSoon: "Próximamente: Digitalización (Scanner).",
    useOCR: "OCR (Texto buscable)",
    ocrWarning: "El OCR hace que el proceso sea mucho más lento",
    ocrProcessing: "Reconocimiento de texto (OCR)...",
    compressPdf: "Compresión de PDF",
    compress: "Comprimir",
    ocrInfo: "Cuando está activado, el PDF se guardará en formato de texto seleccionable",
    ocrConfirm: "El procesamiento OCR puede ser significativamente más lento. ¿Desea activarlo?",
    compressHighlight: "Nuevo: Comprimir archivos PDF",
    rotateLeft: "Girar a la izquierda",
    rotateRight: "Girar a la derecha",
    recrop: "Recortar de nuevo",
    pageShort: "Pág",
    savePdfError: "Error al guardar el PDF editado.",
    about: "Acerca de",
    aboutTitle: "Acerca de Αρχή PDF",
    developedBy: "Creado y desarrollado por L. Stivan e H. Cordeiro",
    openSourceLicenses: "Licenças Open Source",
    version: "Versión",
    manualTitle: "Manual de Usuario",
    manualIntro: "Bienvenido a Αρχή PDF v2.8. Aquí están las principales funcionalidades detalladas:",
    manualOrganize: "Organización y Columnas",
    manualOrganizeText: "Organice sus documentos creando columnas. Puede renombrar cada PDF final, mover páginas entre documentos, pegar imágenes desde el portapapeles (CTRL+V) y seleccionar cuáles exportar.",
    manualAutoCrop: "Recorte Inteligente OpenCV",
    manualAutoCropText: "Nuestra IA detecta los bordes del papel, elimina el fondo y corrige la perspectiva, creando un efecto de escáner profesional al instante.",
    manualEditor: "Edición Profesional de Imagen",
    manualEditorText: "En el editor tienes control total: Rotación de imagen (90°), ajuste de Brillo y Contraste, Recorte Manual de precisión y nueva herramienta de Texto para anotaciones personalizables.",
    manualPdfTools: "Gestión de PDF",
    manualPdfToolsText: "Agregue páginas a PDFs existentes, reordene la secuencia, elimine páginas no deseadas o divida un PDF grande en varios archivos.",
    manualSettings: "Ajustes de IA",
    manualSettingsText: "Utilice 'Compress' para generar archivos ligeros. Active 'OCR AI' para que el texto de sus imágenes sea buscable en el PDF final.",
    pdfEditHighlight: "Nuevo: ¡Edición Completa!",
    pdfEditHighlightText: "¡Ahora puedes recortar páginas de PDF, girar y ajustar la perspectiva individualmente para cada hoja!"
  },
  'el': {
    selectAll: "Επιλογή όλων",
    clearAll: "Καθαρισμός όλων",
    convertToPdf: "Μετατροπή σε PDF",
    saveSeparately: "Αποθήκευση ξεχωριστά",
    saveInGroup: "Αποθήκευση ως ομάδα",
    save: "Αποθήκευση",
    saving: "Αποθήκευση...",
    total: "Σύνολο",
    dragDrop: "Σύρετε ή προσθέστε",
    dropHere: "Αφήστε τα αρχεία εδώ",
    addFiles: "Προσθήκη αρχείων",
    edit: "Επεξεργασία",
    editorTitle: "Επεξεργαστής εικόνας",
    pdfEditorTitle: "Επεξεργαστής PDF",
    undo: "Αναίρεση",
    redo: "Επαναφορά",
    reset: "Επαναφορά στο αρχικό",
    restore: "Επαναφορά παρτίδας",
    cancel: "Ακύρωση",
    confirm: "Επιβεβαίωση επεξεργασίας",
    removeBg: "Αφαίρεση φόντου",
    autoCropBatch: "Αυτόματη περικοπή",
    processing: "Επεξεργασία...",
    language: "Ελληνικά",
    theme: "Θέμα",
    deleteDoc: "Διαγραφή εγγράφου",
    search: "Προεπισκόπηση",
    rotate: "Περιστροφή",
    page: "Σελίδα",
    savePdf: "Αποθήκευση PDF",
    loadingPdf: "Φόρτωση PDF...",
    docSaved: "Τα έγγραφα αποθηκεύτηκαν",
    docSaveError: "Σφάλμα κατά την αποθήκευση εγγράφων",
    openFolder: "Εμφάνιση φακέλου προορισμού",
    folderInfo: "Τα αρχεία αποθηκεύονται στον προεπιλεγμένο φάκελο λήψεων.",
    autoSort: "Αυτόματη ταξινόμηση",
    sorting: "Ταξινόμηση...",
    sortSuccess: "Οι σελίδες ταξινομήθηκαν με επιτυχία",
    sortError: "Σφάλμα κατά την ταξινόμηση σελίδων",
    zoomIn: "Μεγέθυνση",
    zoomOut: "Σμίκρυνση",
    zoomReset: "Επαναφορά ζουμ",
    backToGrid: "Επιστροφή στο πλέγμα",
    viewPage: "Προβολή σελίδας",
    nextPage: "Επόμενο",
    prevPage: "Προηγούμενο",
    batchProcessError: "Σφάλμα κατά την επεξεργασία ορισμένων εικόνων.",
    rightsReserved: "Με επιφύλαξη παντός δικαιώματος",
    supportLink: "Κάντε κλικ εδώ για υποστήριξη",
    footerQuote: '"Και ας μην αποκάμουμε κάνοντας το καλό, γιατί στον δικό του καιρό θα θερίσουμε" — Γαλάτας 6:9',
    brightness: "Φωτεινότητα",
    contrast: "Αντίθεση",
    applyCropError: "Σφάλμα κατά την εφαρμογή της περικοπής.",
    saveError: "Σφάλμα κατά την αποθήκευση.",
    rotateError: "Σφάλμα κατά την περιστροφή της εικόνας.",
    manualCrop: "Χειροκίνητη Περικοπή",
    cropInstructions: "Σύρετε τις γωνίες που εντοπίστηκαν για να προσαρμόσετε την προοπτική.",
    applyCrop: "Εφαρμογή Περικοπής",
    imageTools: "Προσαρμογές",
    addText: "Προσθήκη Κειμένου",
    font: "Γραμματοσειρά",
    color: "Χρώμα",
    size: "Μέγεθος",
    textPlaceholder: "Πληκτρολογήστε το κείμενό σας...",
    removeText: "Αφαίρεση Κειμένου",
    initEditorError: "Σφάλμα κατά την προετοιμασία του προγράμματος επεξεργασίας PDF.",
    renderHighResError: "Σφάλμα κατά την απόδοση της σελίδας υψηλής ανάλυσης.",
    items: "στοιχεία",
    cache: "Προσωρινή μνήμη",
    fileRestored: "Το αρχείο αποκαταστάθηκε.",
    newManual: "Νέο: Εγχειρίδιο v2.8",
    toggleTheme: "Εναλλαγή Θέματος",
    manualClose: "Έγινε, ας ξεκινήσουμε!",
    close: "Κλείσιμο",
    cvLoadError: "Δεν ήταν δυνατή η φόρτωση του OpenCV.js.",
    pdfjsLoadError: "Το PDF.js δεν φορτώθηκε.",
    blobError: "Η δημιουργία Blob απέτυχε.",
    canvasContextError: "Δεν ήταν δυνατή η λήψη του περιβάλλοντος καμβά.",
    pdfLibLoadError: "Η βιβλιοθήκη PDF δεν φορτώθηκε.",
    cropSuccess: "Η περικοπή ολοκληρώθηκε!",
    dropError: "Σφάλμα κατά την απόθεση αρχείου.",
    itemDropError: "Σφάλμα κατά την απόθεση στοιχείου.",
    appTitle: "PDF Temp - Επεξεργαστής Εγγράφων",
    appDescription: "Τοπικός και ασφαλής επεξεργαστής εγγράφων PDF και εικόνων.",
    noDocFound: "Δεν εντοπίστηκε έγγραφο.",
    changelog_v2_8: "v2.8 - ΝΕΟ: Εργαλείο Κειμένου στον Επεξεργαστή, Επικόλληση εικόνων (CTRL+V) στο Kanban και βελτιώσεις UX",
    changelog_v2_7: "v2.7 - ΝΕΟ: Περιστροφή PDF, Περικοπή PDF, οπτικές βελτιώσεις και διορθώσεις μικρών σφαλμάτων",
    changelog_v2_6: "v2.6 - Προηγμένα εργαλεία επεξεργασίας PDF, περικοπή προοπτικής και διορθώσεις σφαλμάτων",
    changelog_v2_5: "v2.5 - Λεπτομερές και διαδραστικό εγχειρίδιο χρήστη",
    changelog_v2_4: "v2.4 - Λειτουργία συμπίεσης PDF υψηλής απόδοσης",
    changelog_v2_3: "v2.3 - Σύστημα αυτόματης ανίχνευσης ενημερώσεων",
    adjustHelp: "Προσαρμόστε την αντίθεση για να βοηθήσετε στην αφαίρεση του φόντου.",
    applyAdjustments: "Εφαρμογή προσαρμογών",
    updateAvailable: "Νέα έκδοση διαθέσιμη",
    updateNow: "Ενημέρωση",
    addPages: "Προσθήκη σελίδων",
    splitPdf: "Διαίρεση PDF",
    splitIntervals: "Εύρος σελίδων",
    splitPlaceholder: "Πχ: 1-3, 5, 8-10",
    splitAction: "Διαίρεση και λήψη",
    splitInvalid: "Μη έγκυρο εύρος. Χρησιμοποιήστε μορφές όπως 1-3 ή 5.",
    comingSoon: "Σύντομα κοντά σας: Σάρωση εγγράφων.",
    useOCR: "OCR (Αναζητήσιμο κείμενο)",
    ocrWarning: "Το OCR καθυστερεί σημαντικά τη διαδικασία",
    ocrProcessing: "Αναγνώριση κειμένου (OCR)...",
    compressPdf: "Συμπίεση PDF",
    compress: "Συμπίεση",
    ocrInfo: "Όταν είναι ενεργοποιημένο, το PDF θα αποθηκευτεί σε μορφή επιλέξιμου κειμένου",
    ocrConfirm: "Η επεξεργασία OCR μπορεί να είναι σημαντικά πιο αργή. Θέλετε να την ενεργοποιήσετε;",
    compressHighlight: "Νέο: Συμπίεση αρχείων PDF",
    rotateLeft: "Περιστροφή αριστερά",
    rotateRight: "Περιστροφή δεξιά",
    recrop: "Περικοπή ξανά",
    pageShort: "Σελ",
    savePdfError: "Σφάλμα κατά την αποθήκευση του επεξεργασμένου PDF.",
    about: "Σχετικά",
    aboutTitle: "Σχετικά με το Αρχή PDF",
    developedBy: "Δημιουργήθηκε από τους L. Stivan και H. Cordeiro",
    openSourceLicenses: "Άδειες ανοιχτού κώδικα",
    version: "Έκδοση",
    manualTitle: "Εγχειρίδιο Χρήστη",
    manualIntro: "Καλώς ήρθατε στο Αρχή PDF v2.8. Εδώ είναι τα κύρια χαρακτηριστικά:",
    manualOrganize: "Οργάνωση και Στήλες",
    manualOrganizeText: "Οργανώστε τα έγγραφά σας δημιουργώντας στήλες. Μπορείτε να μετονομάσετε κάθε PDF, να μετακινήσετε σελίδες, να επικολλήσετε εικόνες από το πρόχειρο (CTRL+V) και να επιλέξετε ποιες θα εξαγάγετε.",
    manualAutoCrop: "Έξυπνη Περικοπή OpenCV",
    manualAutoCropText: "Η AI μας ανιχνεύει τις άκρες του χαρτιού, αφαιρεί το φόντο και διορθώνει την προοπτική, δημιουργώντας ένα εφέ επαγγελματικού σαρωτή.",
    manualEditor: "Επαγγελματική Επεξεργασία Εικόνας",
    manualEditorText: "Στον επεξεργαστή έχετε πλήρη έλεγχο: Περιστροφή εικόνας (90°), ρύθμιση Φωτεινότητας και Αντίθεσης, Χειροκίνητη Περικοπή ακριβείας και νέο εργαλείο Κειμένου για προσαρμόσιμες σημειώσεις.",
    manualPdfTools: "Διαχείριση PDF",
    manualPdfToolsText: "Προσθέστε σελίδες σε υπάρχοντα PDF, αναδιατάξτε τη σειρά, διαγράψτε σελίδες ή χωρίστε ένα PDF σε πολλά αρχεία.",
    manualSettings: "Ρυθμίσεις AI",
    manualSettingsText: "Χρησιμοποιήστε το 'Compress' για ελαφριά αρχεία. Ενεργοποιήστε το 'OCR AI' για αναζητήσιμο κείμενο στο τελικό PDF.",
    pdfEditHighlight: "Νέα: Πλήρης Επεξεργασία!",
    pdfEditHighlightText: "Τώρα μπορείτε να περικόψετε σελίδες PDF, να τις περιστρέψετε και να προσαρμόσετε την προοπτική μεμονωμένα για κάθε φύλλο!"
  },
  'he': {
    selectAll: "בחר הכל",
    clearAll: "נקה הכל",
    convertToPdf: "המר ל-PDF",
    saveSeparately: "שמור בנפרד",
    saveInGroup: "שמור כקבוצה",
    save: "שמור",
    saving: "שומר...",
    total: "סה\"כ",
    dragDrop: "גרור או הוסף",
    dropHere: "שחרר קבצים כאן",
    addFiles: "הוסף קבצים",
    edit: "ערוך",
    editorTitle: "עורך תמונות",
    pdfEditorTitle: "עורך PDF",
    undo: "בטל",
    redo: "בצע שוב",
    reset: "אפס למקור",
    restore: "שחזר אצווה",
    cancel: "ביטול",
    confirm: "אשר עריכה",
    removeBg: "הסר רקע",
    autoCropBatch: "חיתוך אוטומטי",
    processing: "מעבד...",
    language: "עברית",
    theme: "ערכת נושא",
    deleteDoc: "מחק מסמך",
    search: "תצוגה מקדימה",
    rotate: "סובב",
    page: "עמוד",
    savePdf: "שמור PDF",
    loadingPdf: "טוען PDF...",
    docSaved: "המסמך/ים נשמרו",
    docSaveError: "שגיאה בשמירת המסמך/ים",
    openFolder: "הצג תיקיית יעד",
    folderInfo: "הקבצים נשמרים בתיקיית ההורדות המוגדרת כברירת מחדל.",
    autoSort: "מיון אוטומטי",
    sorting: "ממיין...",
    sortSuccess: "העמודים מוינו בהצלחה",
    sortError: "שגיאה במיון העמודים",
    zoomIn: "התקרב",
    zoomOut: "התרחק",
    zoomReset: "אפס זום",
    backToGrid: "חזור לרשת",
    viewPage: "צפה בעמוד",
    nextPage: "הבא",
    prevPage: "הקודם",
    batchProcessError: "שגיאה בעיבוד חלק מהתמונות.",
    rightsReserved: "כל הזכויות שמורות",
    supportLink: "לחץ כאן לתמיכה",
    footerQuote: "\"ואל נלאה מעשות הטוב, כי בעתו נקצר אם לא נרפה\" — גלטיים ו:ט",
    brightness: "בהירות",
    contrast: "ניגודיות",
    applyCropError: "שגיאה בהחלת החיתוך.",
    saveError: "שגיאה בשמירה.",
    rotateError: "שגיאה בסיבוב התמונה.",
    manualCrop: "חיתוך ידני",
    cropInstructions: "גרור את הפינות שזוהו כדי להתאים את הפרספקטיבה.",
    applyCrop: "החל חיתוך",
    imageTools: "התאמות",
    addText: "הוסף טקסט",
    font: "גופן",
    color: "צבע",
    size: "גודל",
    textPlaceholder: "הקלד את הטקסט שלך...",
    removeText: "הסר טקסט",
    initEditorError: "שגיאה באתחול עורך ה-PDF.",
    renderHighResError: "שגיאה ברינדור עמוד ברזולוציה גבוהה.",
    items: "פריטים",
    cache: "מטמון",
    fileRestored: "הקובץ שוחזר.",
    newManual: "חדש: מדריך v2.8",
    toggleTheme: "החלף ערכת נושא",
    manualClose: "הבנתי, בואו נתחיל!",
    close: "סגור",
    cvLoadError: "לא ניתן היה לטעון את OpenCV.js.",
    pdfjsLoadError: "PDF.js לא נטען.",
    blobError: "יצירת Blob נכשלה.",
    canvasContextError: "לא ניתן היה לקבל את הקשר הקנבס.",
    pdfLibLoadError: "ספריית PDF לא נטענה.",
    cropSuccess: "החיתוך הושלם!",
    dropError: "שגיאה בשחרור קובץ.",
    itemDropError: "שגיאה בשחרור פריט.",
    appTitle: "PDF Temp - עורך מסמכים",
    appDescription: "עורך מסמכי PDF ותמונות מקומי ומאובטח.",
    noDocFound: "לא זוהה מסמך.",
    changelog_v2_8: "v2.8 - חדש: כלי טקסט בעורך, הדבקת תמונות (CTRL+V) בקנבן ושיפורי UX",
    changelog_v2_7: "v2.7 - חדש: סיבוב PDF, חיתוך PDF, שיפורים ויזואליים ותיקוני באגים קלים",
    changelog_v2_6: "v2.6 - כלי עריכת PDF מתקדמים, חיתוך פרספקטיבה ותיקוני באגים",
    changelog_v2_5: "v2.5 - מדריך למשתמש מפורט ואינטראקטיבי",
    changelog_v2_4: "v2.4 - תכונת דחיסת PDF בביצועים גבוהים",
    changelog_v2_3: "v2.3 - מערכת זיהוי עדכונים אוטומטית",
    adjustHelp: "כוון ניגודיות כדי לסייע בהסרת הרקע.",
    applyAdjustments: "החל התאמות",
    updateAvailable: "גרסה חדשה זמינה",
    updateNow: "עדכן",
    addPages: "הוסף עמודים",
    splitPdf: "פצל PDF",
    splitIntervals: "טווחי עמודים",
    splitPlaceholder: "למשל: 1-3, 5, 8-10",
    splitAction: "פצל והורד",
    splitInvalid: "טווח לא תקין. השתמש בפורמטים כמו 1-3 או 5.",
    comingSoon: "בבקרוב: סריקת מסמכים.",
    useOCR: "OCR (טקסט שניתן לחיפוש)",
    ocrWarning: "OCR הופך את התהליך לאיטי משמעותית",
    ocrProcessing: "מזהה טקסט (OCR)...",
    compressPdf: "דחיסת PDF",
    compress: "דחוס",
    ocrInfo: "כאשר מופעל, ה-PDF יישמר בפורמט טקסט הניתן לבחירה",
    ocrConfirm: "עיבוד OCR עשוי להיות איטי משמעותית. האם ברצונך להפעיל אותו?",
    compressHighlight: "חדש: דחיסת קבצי PDF",
    rotateLeft: "סובב שמאלה",
    rotateRight: "סובב ימינה",
    recrop: "חתוך מחדש",
    pageShort: "עמ'",
    savePdfError: "שגיאה בשמירת ה-PDF הערוך.",
    about: "אודות",
    aboutTitle: "אודות Αρχή PDF",
    developedBy: "נוצר ופותח על ידי L. Stivan ו-H. Cordeiro",
    openSourceLicenses: "רישיונות קוד פתוח",
    version: "גרסה",
    manualTitle: "מדריך למשתמש",
    manualIntro: "ברוכים הבאים ל-Αρχή PDF v2.8. להלן התכונות העיקריות:",
    manualOrganize: "ארגון ועמודות",
    manualOrganizeText: "ארגן את המסמכים שלך על ידי יצירת עמודות. אתה יכול לשנות את השם של כל PDF, להעביר עמודים, להדביק תמונות מלוח הגזירים (CTRL+V) ולבחור מה לייצא.",
    manualAutoCrop: "חיתוך חכם OpenCV",
    manualAutoCropText: "הבינה המלאכותית שלנו מזהה את קצוות הנייר, מסירה את הרקע ומתקנת את הפרספקטיבה, ויוצרת אפקט סורק מקצועי מיידי.",
    manualEditor: "עריכת תמונה מקצועית",
    manualEditorText: "בעורך יש לך שליטה מלאה: סיבוב תמונה (90°), כוונון בהירות וניגודיות, חיתוך ידני מדויק וכלי טקסט חדש להערות הניתנות להתאמה אישית.",
    manualPdfTools: "ניהול PDF",
    manualPdfToolsText: "הוסף עמודים ל-PDF קיימים, שנה את סדר העמודים, מחק עמודים לא רצויים או פצל PDF לקבצים מרובים.",
    manualSettings: "הגדרות בינה מלאלאכותית",
    manualSettingsText: "השתמש ב-'Compress' לקבצים קלים. אפשר 'OCR AI' כדי שהטקסט בתמונות שלך יהפוך לניתן לחיפוש ב-PDF הסופי.",
    pdfEditHighlight: "חדש: עריכה מלאה!",
    pdfEditHighlightText: "כעת תוכלו לחתוך עמודי PDF, לסובב ולהתאים פרספקטיבה בנפרד לכל גיליון!"
  }
};
